### ISSUE TITLE
discussion on media folders

### ISSUE THREAD

**Issue by HerbFargus** [mattrixk/es-toolkit#2]
I'd like to get other peoples opinions on their preferences for the media. The release will place them in the rom folders for maximum portability, but should we:

1. Keep everything in one media folder
2. Split it into 3 folders: images, videos, marquees
3. Keep everything in the media folder but then split it by images, videos, and marquees

**Comment by mattrixk** [comment]
My personal preference would be just keep everything in the one folder, but I do agree that we should ask what others think.

The fake roms in the Toolkit have more than just those 3 things though. Along with Videos and Logos, they have Screenshots, Box Art, Fan Art, and Cartridges. Should they each go into their own folders, or maybe an "extra" or "misc" folder?

**Comment by HerbFargus** [comment]
But with the box art fan art etc they can be mixed with uxs into one image though right? 

At that point there may be no end to the splitting of folders

**Comment by mattrixk** [comment]
They can be downloaded with UXS as single images, or as a Mix image, it's up to the person scraping the roms. I originally scraped all the single images so users had a bunch of different artwork they could use to mock-up their designs if they wanted to. 

It's not really something the average user is going to do, so it's not really something to worry about, I just wanted to give people as many tools as possible to make the designs they wanted.

**Comment by HerbFargus** [comment]
you could argue that uxs is a bit of a hack due to the limitations of ES, whereas many other theme engines of sorts can actually render each type of image independently of one another. 

But anyways for a basic kit for inital tests, I suppose its simpler to just keep it in one and let the user modify as they please.

**Comment by mattrixk** [comment]
>for a basic kit for inital tests, I suppose its simpler to just keep it in one and let the user modify as they please

I think that's best. I made the Toolkit originally to help people with making themes, so it's not really important where the images, videos and gamelists are, so long as they work when someone copies them over to their copy of ES (or *our* copy of ES). I think if we go splitting them up into separate folders it's just making more work for us.

If a person wants to set up their personal setup that way, then more power to them, but it's not something we need to concern ourselves with.

>many other theme engines of sorts can actually render each type of image independently of one another.

I'd love it if ES could eventually do that, but I'm okay with how it is currently. I put it in with the proposed tagging/filtering/sorting changes, in that I'd imagine that would be a pretty big change, and would probably end up being ES2 and being completely incompatible with ES.

**Comment by HerbFargus** [comment]
Ok. We'll leave it as is with only the media folder
